### ISSUE TITLE
Become an awesome

### ISSUE THREAD

**Issue by danielgomezrico** [ashleygwilliams/breakfast-repo#31]
Will be great if you can talk about each link and why it was important to become an awesome!

https://github.com/sindresorhus/awesome

**Comment by jalcine** [comment]
What's the advantage of this @danielgomezrico? Sounds like in order to be an awesome, a bit more labor than what's been currently shuffled is needed :crying_cat_face: . There's also [JanVanRyswyck's **awesome-talks**](https://github.com/JanVanRyswyck/awesome-talks).

(waits for @ashleygwilliams to weigh in)

**Comment by ashleygwilliams** [comment]
yeah hrm. that would be great, but the goal of this repo is primarily for me to foster a sustainable behavior, i.e. learning at least one new thing everyday. i worry that extra effort would make me less likely to do it. it's an interesting thought though, and maybe i'll do it for some talks. but probably not make it a habit, at least not any time soon.

**Comment by danielgomezrico** [comment]
Is just that is a way to have a list of things with some conventions so anyone that finds your list may use it someway and not discover how you order things or something, yeah, not a big deal and you are right, can become tedious at the beginning, but once you do it may help to clear what you learn about the videos or lessons writing the little description of the video or to find it faster latter :)
