### ISSUE TITLE
Rick Astley - Never Gonna Give You Up

### ISSUE THREAD

**Issue by wowaname** [ashleygwilliams/breakfast-repo#44]

**Comment by steveklabnik** [comment]
har har :)

**Comment by ashleygwilliams** [comment]
not funny.

**Comment by installgen2** [comment]
HAHAHHAHAHHAHAH this is some **DANK SHIT** right here @wowaname XD very funny issue meme

**Comment by emanawow** [comment]
Any reason for "not funny" when 2 people have expressed their sympathy?

**Comment by rtorr** [comment]
Close comments :pray:?

**Comment by pikaj00** [comment]
Lol. This issue is still not resolved appropriately‎. I will not be pulling until we can never give this up!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: emanawowSent: Saturday, November 14, 2015 7:57 PMTo: ashleygwilliams/breakfast-repoReply To: ashleygwilliams/breakfast-repoSubject: Re: [breakfast-repo] Rick Astley - Never Gonna Give You Up (#44)Any reason for "not funny" when 2 people have expressed their sympathy?

—Reply to this email directly or view it on GitHub.

**Comment by pikaj00** [comment]
I demand a solution to this issue!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Richard TorruellasSent: Saturday, November 14, 2015 7:59 PMTo: ashleygwilliams/breakfast-repoReply To: ashleygwilliams/breakfast-repoSubject: Re: [breakfast-repo] Rick Astley - Never Gonna Give You Up (#44)Close comments ? 

—Reply to this email directly or view it on GitHub.
